# Site settings 配置站点
title: '老痰酸菜面儿'
description: '谢谢你'
keywords: '老痰, 老痰酸菜面儿, 痰工, 痰宝, 鲨鱼痰痰, 团建, team build, 珂珂, 苏恩, 米儿, 西瓜妹妹'
url: 'https://grandtanfans.github.io' # your host

# nav 中文字符空格：&emsp;
nav: # 最佳体验 六个标签 且最好每个标签不超过4中文字
  首页: '/'
  标签: '/tags.html'
  时间线: '/timeline.html'
  关于老痰: '/about.html'
  友情链接: '/friendLink.html'

# 博主
author: true
name: '老痰酸菜面儿应援团'
NickName: '痰黄刀'
webtitle: '老痰酸菜面儿粉丝团部落格'
bio: '本博客为老痰女粉向众多主页之一。仅更新和痰的相关内容。<br/>博主并非痰本人或主持人员，本博客观点也只是博主的个人想法，不代表老痰及超话管理团队的任何立场。<br/>P.S.: 使用 PC 端查看本页面时，将鼠标指针放到老痰图腾上有惊喜。<br/>P.S.2: 使用 PC 端浏览器查看本博客内容时，地址栏或标签页左侧有圣诞彩蛋。'
about: true
aboutyou: '老痰者，处女座生人，俗名痰咏麟，法号鲨鱼痰痰，广东肇庆人也。<br/>痰风流倜傥，其美髪绝类坐拥女粉无数之赵又廷。旁人观之，皆以为痰之恰到女粉可期也。<br/>痰于建筑艺术颇有钻研，位除项目经理，有高级工程师之才，苟全产值于工地，深得人心，尤为财会、预算、人事所喜；其人宽和温雅，至情至性。尝闻其心仪之某知名主播已有天蝎座男友，悲不自胜，乃长号，歌此主播之成名曲《三角题》以悼良会之永绝。诸女粉闻是曲悉皆泪阑干，于痰好感更甚，盖徒慕痰工之高义也。<br/>痰性喜团建，已获一级团队建造师之认证。尝于夜深人静之时，观苏、米诸人之舞，振臂一嘶，则有弹幕此起彼伏，甚欢；曾接连前往数个直播间套娃，入则莺歌燕舞，出则屏幕已黑，有三国赵子龙七进七出之威。老痰之德隆望尊，可见一斑。<br/>痰亦好音律。尝歌《约腚》《七友》《Lonely Christmas》，余音绕梁三日而不绝。闻者咸掩面涕零，良久弗能止。'
portraits: '/assets/profile.jpg' # your portraits image file path

# SNS
SNS: true
SNS-icon: #['Facebook', 'weibo', 'qq', 'github', 'Dribbble', 'Twitter', 'instagram', 'weixin', 'Codepen']
  mail: 'mailto:abc@gmail.com'
  weixin: '' # 你的微信二维码存放的地址
  qq: '' # 你的qq二维码存放的地址 or http://wpa.qq.com/msgrd?v=3&uin='你的QQ号'&site=qq&menu=yes
  github: ''
  Codepen: ''
  weibo: ''
  instagram: ''
  Twitter: ''
  Dribbble: ''
  Facebook: ''
  Google: ''
  zhihu: ''
  juejin: ''
  twitch: ''

# 分页
paginate: 8
paginatepath: ['page:num']

# since
footer:
  since: 2017

# Markdown
markdown: kramdown
kramdown:
  input: GFM
# 代码高亮 使用rouge
highlighter: rouge
# 代码高亮主题使用pygments主题: autumn\ default\ emacs\ friendly\ manni\ murphy\ pastie\ perldoc\ tango 任选一个你喜欢的主题名称填在下面的单引号中
pygmentsTheme: 'default'

# 友情链接
friends:
  老痰新浪微博超话首页: 'https://www.weibo.com/p/100808c9bf185bddd18c52092ca1528b4d683a'
  康师傅老痰酸菜面斗鱼直播间: 'https://www.douyu.com/2295410'
  老痰新浪微博粉丝群链接: 'https://weibo.com/p/2304914468772696158205'
  存放老痰麻醉剂的医药箱之一: 'https://www.zybuluo.com/NGA-8RYG2LCY/note/1648362'
  老痰个人新浪微博首页: 'https://weibo.com/u/1790149570'
  老痰个人绿洲移动端首页: 'https://m.oasis.weibo.cn/v1/h5/share?uid=1790149570'
  米儿啊i 斗鱼直播间: 'https://www.douyu.com/52011'
  米儿个人新浪微博首页: 'https://weibo.com/u/5976742820'
  苏恩Olivia 斗鱼直播间: 'https://www.douyu.com/42666'
  苏恩个人新浪微博首页: 'https://weibo.com/u/6051078087'
  维乐个人新浪微博首页: 'https://weibo.com/u/6493636275'
  维乐新浪微博超话首页: 'https://weibo.com/p/100808f256ebff513f26d7046caa5556cb373d'
  Sylvia维乐斗鱼直播间: 'https://www.douyu.com/3742334'

# 评论 最佳体验 在disqus、livere和Gitment之间三选一
# disqus 评论
disqus: false
disqus_url: '' # https://abc.disqus.com/embed.js
# 来必力评论
livere: true
livere_uid: 'MTAyMC80ODExNi8yNDYxMw==' # MTAyMC8zNDI2OS8xMDgwNg==
# Gitment评论 OAuth Application
Gitment: false
Gitment_owner: ''  # github用户名
Gitment_repo: ''  # github博客存放的仓库名
client_id: ''  # 注册 OAuth Application 后获得的 client_id
client_secret: ''  # 注册 OAuth Application 后获得的 client_secret

# Share : weibo, qq, wechat, tencent, douban, qzone, linkedin, diandian, facebook, twitter, google
social-share: true
social-share-items: ['qq', 'wechat', 'weibo', 'twitter', 'facebook']

# 百度统计 在baidu-url里填写自己相关的url代码
baidu: true
baidu-url: ''
# 谷歌分析 在google-ID里填写自己在谷歌分析获得的追踪ID
google: false
google-ID: ''

# 博客头信息备选颜色（该部分在站点中不充当站点变量，将其写在post的头信息中用来充当页面变量）
color: rgb(154,133,255) rgb(255,90,90) rgb(255,210,32) rgb(98,170,255)
